sudo: required

language: go

go:
  - 1.9

branches:
  only:
  - master

install:
  - wget https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz -O /tmp/glide-v0.12.3-linux-amd64.tar.gz
  - tar -xvf /tmp/glide-v0.12.3-linux-amd64.tar.gz
  - export PATH=$PATH:$PWD/linux-amd64/
  - make install-deps

script:
  - make test-coverage
  - make travis-release

env:
  global:
  - ENCRYPTION_LABEL: "e53e59254cc7"

after_success:
  - make send-codecov-ci
