language: go

go:
  - 1.6
  - 1.7

install:
  - wget https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz -O /tmp/glide-v0.12.3-linux-amd64.tar.gz
  - tar -xvf /tmp/glide-v0.12.3-linux-amd64.tar.gz
  - export PATH=$PATH:$PWD/linux-amd64/
  - make install deps

script:
  - make test-coverage

after_success:
  - make send-codecov-ci
