name: Main

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      run: make test-coverage

    - name: Send coverage to codecov
      uses: codecov/codecov-action@v3
